// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJIFMczWMdGCNAai2SuKCEa9bhVif4KE',
    appId: '1:480216592378:web:65003c3d33d271da0afe43',
    messagingSenderId: '480216592378',
    projectId: 'roseliveuser',
    authDomain: 'roseliveuser.firebaseapp.com',
    storageBucket: 'roseliveuser.firebasestorage.app',
    measurementId: 'G-0EFNJQH7RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ZNx9drww5aFF9upOgy-zW5wDfA1cSIg',
    appId: '1:480216592378:android:f06494b03a97065c0afe43',
    messagingSenderId: '480216592378',
    projectId: 'roseliveuser',
    storageBucket: 'roseliveuser.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcSkDuTtdiUTIWIUQi2wL73J3QnZgYIhs',
    appId: '1:480216592378:ios:2b83ff15370ac2740afe43',
    messagingSenderId: '480216592378',
    projectId: 'roseliveuser',
    storageBucket: 'roseliveuser.firebasestorage.app',
    iosBundleId: 'com.example.varagorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcSkDuTtdiUTIWIUQi2wL73J3QnZgYIhs',
    appId: '1:480216592378:ios:2b83ff15370ac2740afe43',
    messagingSenderId: '480216592378',
    projectId: 'roseliveuser',
    storageBucket: 'roseliveuser.firebasestorage.app',
    iosBundleId: 'com.example.varagorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCJIFMczWMdGCNAai2SuKCEa9bhVif4KE',
    appId: '1:480216592378:web:86f0c642e3f3aca60afe43',
    messagingSenderId: '480216592378',
    projectId: 'roseliveuser',
    authDomain: 'roseliveuser.firebaseapp.com',
    storageBucket: 'roseliveuser.firebasestorage.app',
    measurementId: 'G-D134KG9FCY',
  );
}
